version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - run:
        name: Decode dotenv file
        command: echo $ENV_FILE | base64 --decode > .env
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test
